# Generated by Django 5.0.4 on 2024-08-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0007_student_admission_date'),
        ('users', '0004_alter_customuser_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=550, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half-yearly', 'Half-Yearly'), ('yearly', 'Yearly')], max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('required_for_all', models.BooleanField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.institute')),
            ],
        ),
        migrations.CreateModel(
            name='FeeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.fee')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feeversion')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trx_id', models.CharField(blank=True, default='', max_length=32, unique=True, verbose_name='Transaction ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('fail', 'Fail'), ('hold', 'Hold')], max_length=30)),
                ('bills', models.ManyToManyField(related_name='bill', to='finance.bill')),
            ],
        ),
    ]
