# Generated by Django 5.0.4 on 2024-08-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_mode_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
