# Generated by Django 5.0.4 on 2024-09-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payment_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bills',
            field=models.ManyToManyField(related_name='bills', to='finance.bill'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trx_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=32, unique=True, verbose_name='Transaction ID'),
        ),
    ]
