# Generated by Django 5.0.4 on 2024-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_payment_bills_alter_payment_trx_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bills',
            field=models.ManyToManyField(related_name='payments', to='finance.bill'),
        ),
    ]
