# Generated by Django 5.0.4 on 2024-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_payment_bills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='trx_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=8, unique=True, verbose_name='Transaction ID'),
        ),
    ]
