# Generated by Django 5.0.4 on 2025-01-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_payment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_service_charge_bdt', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_original', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gateway_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_service_charge_usd', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_card_bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_card_bank_country', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('card_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.IntegerField()),
                ('pay_status', models.CharField(max_length=50)),
                ('success_url', models.URLField(blank=True, null=True)),
                ('fail_url', models.URLField(blank=True, null=True)),
                ('cus_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cus_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cus_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_merchant', models.CharField(blank=True, max_length=10, null=True)),
                ('convertion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('other_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_txnid', models.CharField(blank=True, max_length=255, null=True)),
                ('epw_txnid', models.CharField(blank=True, max_length=255, null=True)),
                ('mer_txnid', models.CharField(blank=True, max_length=255, null=True)),
                ('store_id', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('store_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_txn', models.CharField(blank=True, max_length=255, null=True)),
                ('card_type', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_card_risklevel', models.CharField(blank=True, max_length=2, null=True)),
                ('pg_error_code_details', models.CharField(blank=True, max_length=255, null=True)),
                ('opt_a', models.CharField(blank=True, max_length=255, null=True)),
                ('opt_b', models.CharField(blank=True, max_length=255, null=True)),
                ('opt_c', models.CharField(blank=True, max_length=255, null=True)),
                ('opt_d', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
