# Generated by Django 5.0.4 on 2025-01-24 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_epayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='epayment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.epayment'),
        ),
    ]
