# Generated by Django 5.0.4 on 2024-06-29 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
