# Generated by Django 5.0.4 on 2024-06-20 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_klass_students_alter_klass_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=120)),
                ('fathers_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=220)),
                ('birth_date', models.DateField()),
                ('birth_certificate_no', models.CharField(max_length=220)),
                ('nid_no', models.CharField(blank=True, max_length=220, null=True)),
                ('image', models.ImageField(upload_to='documents\\student\\<student_id>')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.klass')),
            ],
        ),
        migrations.AlterField(
            model_name='klass',
            name='students',
            field=models.ManyToManyField(related_name='student', to='base.student'),
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents\\student\\<student.pk>')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
    ]
