# Generated by Django 5.0.4 on 2024-07-09 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_klass_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('presents', models.BooleanField()),
                ('cause', models.CharField(blank=True, choices=[('leave', 'Leave'), ('holiday', 'Holiday'), ('weekend', 'Weekend')], max_length=220, null=True)),
                ('remarks', models.CharField(blank=True, max_length=220, null=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.klass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'student', 'klass')},
            },
        ),
    ]
