# Generated by Django 5.0.4 on 2024-06-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_klass_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='document_title',
            field=models.CharField(default='Nothing', max_length=120),
            preserve_default=False,
        ),
    ]
