# Generated by Django 5.0.4 on 2024-07-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_klass_teachers_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='cause',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
