# Generated by Django 5.0.4 on 2024-07-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_attendence_remarks_alter_attendence_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(auto_now_add=True, default='2024-07-06'),
            preserve_default=False,
        ),
    ]
