# Generated by Django 5.0.4 on 2024-06-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_studentdocument_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='klass',
        ),
    ]
