# Generated by Django 5.0.4 on 2024-06-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_student_klass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocument',
            name='student',
        ),
        migrations.DeleteModel(
            name='Klass',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentDocument',
        ),
    ]
