# Generated by Django 5.0.4 on 2024-08-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_student_admission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Third-Gender', 'third-gender')], default='male', max_length=50),
        ),
        migrations.CreateModel(
            name='AdditionalStudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('value', models.CharField(blank=True, max_length=512, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
            options={
                'unique_together': {('student', 'title')},
            },
        ),
    ]
