# Generated by Django 5.0.4 on 2024-08-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_student_gender_additionalstudentinfo'),
        ('users', '0004_alter_customuser_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalStudentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.institute')),
            ],
            options={
                'unique_together': {('institute', 'title')},
            },
        ),
        migrations.DeleteModel(
            name='AdditionalStudentInfo',
        ),
    ]
