# Generated by Django 5.0.4 on 2024-06-21 06:32

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0008_remove_studentdocument_student_delete_klass_and_more'),
        ('users', '0003_alter_customuser_institute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=120)),
                ('fathers_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=220)),
                ('birth_date', models.DateField()),
                ('birth_certificate_no', models.CharField(max_length=220)),
                ('nid_no', models.CharField(blank=True, max_length=220, null=True)),
                ('image', models.ImageField(upload_to=base.models.Student.folder_convention)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.institute')),
            ],
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('teachers', models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='student', to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to=base.models.Student.folder_convention)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
    ]
