# Generated by Django 5.0.4 on 2024-06-21 06:34

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='image',
            field=models.ImageField(upload_to=base.models.StudentDocument.folder_convention),
        ),
    ]
