# Generated by Django 5.0.4 on 2024-10-12 11:04

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_additionalstudentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalstudentfield',
            name='field_type',
            field=models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('file', 'File')], default='text', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionalstudentfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='additionalstudentinfo',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.AdditionalStudentInfo.folder_convention),
        ),
        migrations.AlterField(
            model_name='additionalstudentinfo',
            name='value',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
