# Generated by Django 5.0.4 on 2025-01-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_subject_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('student', 'subject')},
        ),
        migrations.RemoveField(
            model_name='mark',
            name='klass',
        ),
    ]
