# Generated by Django 5.0.4 on 2025-01-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_student_account_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='banned_account',
            field=models.BooleanField(default=False),
        ),
    ]
