# Generated by Django 5.0.4 on 2025-02-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_student_banned_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='admission_open',
            field=models.BooleanField(default=False),
        ),
    ]
