# Generated by Django 5.0.4 on 2024-06-24 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.institute'),
        ),
    ]
